# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

jobs:
- job:
  variables:
    x: 1
    a: $[counter(1, 0)]
    steps:
    - bash: echo $(x) is incrmented by 1 to get $(a)

steps:
- task: Xcode@4
  inputs:
    actions: 'build'
    scheme: 'TestIOSApp'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
