# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

variables:
  releaseNumber: 1908
  majorVersion: 1
  minorVersion: 0
  patchInitialVersion: 0
  patchVersion: $[counter(variables['releaseNumber'], variables['patchInitialVersion'])]

name: $(majorVersion).$(minorVersion).$(patchVersion)
jobs:
- job:
  pool:
    vmImage: 'macOS-latest'
  steps:
    - bash: echo $(x) is incremented by 1 to get build number as $(buildVersion)
    - bash: echo Azure Build Number Before Update $(Build.BuildNumber)
    - bash: echo Write-Host "##vso[task.setvariable variable=Build.BuildNumber;]$(majorVersion).$(minorVersion).$(patchVersion)"
    - bash: echo Azure Build Number After Update $(Build.BuildNumber)
    - task: Xcode@4
      inputs:
        actions: 'build'
        scheme: 'TestIOSApp'
        sdk: 'iphoneos'
        configuration: 'Release'
        xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
        xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

