# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

jobs:
- job:
  pool:
    vmImage: 'macOS-latest'
  variables:
    name: $(BuildDefinitionName)-$(Rev:.r)
    x: 11
    a: $[counter(variables['x'], 20)]
  steps:
    - bash: echo $(x) is incremented by 5 to get $(a)
    - bash: echo Build Definition Name - $(name)
    - bash: echo Build is equal to $(Build.BuildNumber)
    - task: Xcode@4
      inputs:
        actions: 'build'
        scheme: 'TestIOSApp'
        sdk: 'iphoneos'
        configuration: 'Release'
        xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
        xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

